# Generated by Django 3.1 on 2021-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
