# Generated by Django 3.1 on 2021-04-28 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_managment', '0002_auto_20210427_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='offer',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
