# Generated by Django 3.1 on 2021-05-25 15:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0012_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer_managment', '0003_auto_20210428_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status_kanban', models.IntegerField(blank=True, null=True)),
                ('stage_candidate', models.IntegerField(blank=True, choices=[(1, 'a trier'), (2, 'a appeler'), (3, 'entretien rh'), (4, 'entretien operationnel'), (5, 'retenu')], default=1, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recruiters', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_managment.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer_managment.offer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
