# Generated by Django 3.1 on 2021-06-07 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer_managment', '0007_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='recruiter',
            field=models.ManyToManyField(blank=True, null=True, related_name='recruiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
