# Generated by Django 3.1 on 2021-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_managment', '0008_auto_20210607_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'new'), (2, 'en traitement'), (3, 'cloturer')], default=1, null=True),
        ),
    ]
