# Generated by Django 3.1 on 2022-03-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_managment', '0012_auto_20220301_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contactCandidate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='contactEntreprise',
        ),
    ]
