# Generated by Django 3.1 on 2022-03-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0018_remove_document_is_valid'),
        ('referentiel_managment', '0008_auto_20210416_1727'),
        ('offer_managment', '0013_auto_20220302_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contactCandidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate_managment.candidate'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contactEntreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referentiel_managment.contact'),
        ),
    ]
