# Generated by Django 3.1 on 2022-03-03 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_managment', '0014_auto_20220303_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='contactCandidate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='contactEntreprise',
        ),
        migrations.AddField(
            model_name='appointment',
            name='internParticipants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contactCandidate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contactEntreprise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
    ]
