# Generated by Django 3.1 on 2022-03-04 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_managment', '0015_auto_20220303_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='contactCandidate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contactEntreprise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='internParticipants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=None, null=True, size=None),
        ),
    ]
