# Generated by Django 3.1 on 2022-03-07 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate_managment', '0020_auto_20220304_1521'),
        ('referentiel_managment', '0008_auto_20210416_1727'),
        ('offer_managment', '0017_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contactCandidate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='contactCandidate',
            field=models.ManyToManyField(blank=True, null=True, related_name='contactCandidate', to='candidate_managment.Candidate'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='contactEntreprise',
        ),
        migrations.AddField(
            model_name='appointment',
            name='contactEntreprise',
            field=models.ManyToManyField(blank=True, null=True, related_name='contactEntreprise', to='referentiel_managment.Company'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='internParticipants',
        ),
        migrations.AddField(
            model_name='appointment',
            name='internParticipants',
            field=models.ManyToManyField(blank=True, null=True, related_name='internParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
