# Generated by Django 3.1 on 2022-03-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_managment', '0018_auto_20220307_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='contactCandidate',
            new_name='candidates',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='contactEntreprise',
            new_name='entreprises',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='internParticipants',
            new_name='participants',
        ),
    ]
