# Generated by Django 3.1 on 2022-03-08 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0020_auto_20220304_1521'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referentiel_managment', '0008_auto_20210416_1727'),
        ('offer_managment', '0019_auto_20220308_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='participants',
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, related_name='candidates', to='candidate_managment.Candidate'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='entreprises',
            field=models.ManyToManyField(blank=True, null=True, related_name='entreprises', to='referentiel_managment.Company'),
        ),
    ]
