# Generated by Django 3.1 on 2022-03-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_managment', '0020_auto_20220308_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='contact_participants',
            new_name='participants',
        ),
    ]
