# Generated by Django 3.1 on 2022-04-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_advantages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceadvantages',
            name='category',
            field=models.CharField(choices=[('MONTANT_FIXE', 'Montant Fixe'), ('PRET', 'Prêt')], default='MONTANT_FIXE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resourceadvantages',
            name='frequency',
            field=models.CharField(choices=[('PONCTUELLE', 'Ponctuelle'), ('JOURNALIERE', 'Journalière'), ('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('SEMSTRIELLE', 'Semestrielle'), ('ANNUELLE', 'Annuelle')], default='PONCTUELLE', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resourceadvantages',
            name='is_montant_fixe',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='resourceadvantages',
            name='load_rate',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='resourceadvantages',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
