# Generated by Django 3.1 on 2022-04-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0003_auto_20220411_1145'),
        ('business_unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='business_unit_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_managment.profile'),
        ),
    ]
