# Generated by Django 3.1 on 2022-05-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0010_auto_20220516_0840'),
        ('business_unit', '0002_businessunit_business_unit_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='business_unit_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_managment.profile'),
        ),
    ]
