# Generated by Django 3.1 on 2022-05-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0003_auto_20220516_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='business_unit_manager',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='business_unit_name',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='legal_agency',
        ),
    ]
