# Generated by Django 3.1 on 2022-05-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_unit', '0004_auto_20220520_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
    ]
