# Generated by Django 3.1 on 2020-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_token',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_token_expired_at',
            field=models.DateTimeField(null=True),
        ),
    ]
