version: '3'

services:
  web_e_hiring:
    image: registry.gitlab.com/aakrout/e_hiring_core:v1
    environment:
      - RESET_PASSWORD_LINK
      - DJANGO_ENV=development
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DJANGO_RUN_MIGRATION="on"
      - SITE_DOMAINE_NAME
      - POSTGRES_USER
      - POSTGRES_DB_DEFAULT
      - POSTGRES_DB_DEV
      - ALLOWED_HOSTS
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - uploaded_media:/app/src/media
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.scp-e_hiring-staging-back.rule=Host(`ehiring-api.infinitymgt.fr`)"
        - "traefik.http.routers.scp-e_hiring-staging-back.entrypoints=websecure"
        - "traefik.http.routers.scp-e_hiring-staging-back.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.scp-e_hiring-staging-back-srv.loadbalancer.server.port=8080"

volumes:
  uploaded_media:

networks:
  default:
    external:
      name: traefik-net
