# Generated by Django 3.1 on 2022-05-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20220512_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_access_canidates',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_access_resources',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_validate_timesheet',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
    ]
