# Generated by Django 3.1 on 2022-05-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20220512_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
