# Generated by Django 3.1 on 2020-10-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDBConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_config', models.CharField(max_length=255, unique=True)),
                ('auth_field', models.CharField(max_length=255, unique=True)),
                ('db_name', models.CharField(max_length=150)),
            ],
        ),
    ]
