# Generated by Django 3.1 on 2022-04-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_state', '0001_initial'),
        ('user_managment', '0003_auto_20220411_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='business_unit_manager',
            field=models.BooleanField(default=False, null=True),
        ),
        
        migrations.AddField(
            model_name='profile',
            name='user_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='resource_state.resourcestate'),
        ),
    ]
