# Generated by Django 3.1 on 2022-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0004_auto_20220413_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_unit_manager',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
