# Generated by Django 3.1 on 2022-05-13 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0006_auto_20220512_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, default='email@example.com', max_length=50, null=True), null=True, size=None),
        ),
    ]
