# Generated by Django 3.1 on 2022-05-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0008_auto_20220515_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
