# Generated by Django 3.1 on 2022-05-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_state', '0001_initial'),
        ('user_managment', '0010_auto_20220516_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_state',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resource_state.resourcestate'),
        ),
    ]
