# Generated by Django 3.1 on 2022-05-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_state', '0001_initial'),
        ('user_managment', '0012_auto_20220516_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_state',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_state.resourcestate'),
        ),
    ]
