# Generated by Django 3.1 on 2022-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0013_auto_20220516_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_dob',
            field=models.DateField(null=True),
        ),
    ]
