# Generated by Django 3.1 on 2022-05-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_state', '0001_initial'),
        ('user_managment', '0014_auto_20220518_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_state',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_state',
            field=models.ManyToManyField(to='resource_state.ResourceState'),
        ),
    ]
