# Generated by Django 3.1 on 2022-06-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0015_remove_legalagency_agency_logo'),
        ('user_managment', '0017_auto_20220521_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal_agency.businessunit'),
        ),
    ]
