# Generated by Django 3.1 on 2022-06-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0018_profile_business_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_unit',
        ),
    ]
