# Generated by Django 3.1 on 2022-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('agency_email', models.EmailField(max_length=50)),
                ('agency_address', models.CharField(max_length=50)),
                ('agency_postal_code', models.IntegerField()),
                ('agency_city', models.CharField(max_length=50)),
                ('agency_country', models.CharField(max_length=50)),
                ('agency_legal_status', models.CharField(max_length=50)),
                ('load_factor', models.IntegerField()),
                ('load_rate', models.IntegerField()),
                ('number_of_days_open', models.IntegerField()),
            ],
        ),
    ]
