# Generated by Django 3.1 on 2022-05-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0003_businessunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='business_unit_name',
            field=models.CharField(max_length=100),
        ),
    ]
