# Generated by Django 3.1 on 2022-05-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0016_auto_20220518_1638'),
        ('legal_agency', '0004_auto_20220520_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='business_unit_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_managment.profile'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='legal_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal_agency.legalagency'),
        ),
    ]
