# Generated by Django 3.1 on 2022-05-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0006_auto_20220521_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalagency',
            options={'permissions': [('activate_legalagency', 'Can activate legal agency')]},
        ),
    ]
