# Generated by Django 3.1 on 2022-05-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0007_auto_20220521_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'permissions': [('assign_manager', 'Can assign manager')]},
        ),
    ]
