# Generated by Django 3.1 on 2022-06-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0008_auto_20220524_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='legal_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_unit_set', to='legal_agency.legalagency'),
        ),
    ]
