# Generated by Django 3.1 on 2022-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0009_auto_20220601_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalagency',
            name='agency_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
