# Generated by Django 3.1 on 2022-06-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0010_auto_20220601_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalagency',
            name='number_of_days_open',
        ),
    ]
