# Generated by Django 3.1 on 2022-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0011_remove_legalagency_number_of_days_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalagency',
            name='number_of_days_open',
            field=models.IntegerField(null=True),
        ),
    ]
