# Generated by Django 3.1 on 2022-06-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0012_legalagency_number_of_days_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalagency',
            name='load_factor',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='legalagency',
            name='load_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
