# Generated by Django 3.1 on 2022-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0013_auto_20220603_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalagency',
            name='agency_logo',
            field=models.ImageField(blank=True, null=True, upload_to='LegalAgency/Photo'),
        ),
        migrations.AlterField(
            model_name='legalagency',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
