# Generated by Django 3.1 on 2022-06-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0014_auto_20220616_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalagency',
            name='agency_logo',
        ),
    ]
