# Generated by Django 3.1 on 2022-07-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0015_remove_legalagency_agency_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalagency',
            name='is_deleted',
        ),
    ]
