# Generated by Django 3.1 on 2022-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0019_remove_profile_business_unit'),
        ('legal_agency', '0016_remove_legalagency_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='business_unit_manager',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='business_unit_manager',
            field=models.ManyToManyField(to='user_managment.Profile'),
        ),
    ]
