# Generated by Django 3.1 on 2022-04-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
       
        ('user_managment', '0004_auto_20220413_0749'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.activitytype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.sheet'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='user_managment.profile'),
        ),
    ]
