# Generated by Django 3.1 on 2022-05-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20220413_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet',
            options={'permissions': [('validate_timesheet', 'Can validate timesheet'), ('invalidate_timesheet', 'Can invalidate timesheet')]},
        ),
    ]
