# Generated by Django 3.1 on 2022-06-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0015_remove_legalagency_agency_logo'),
        ('timesheet', '0004_auto_20220517_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='business_unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal_agency.businessunit'),
        ),
    ]
