# Generated by Django 3.1 on 2022-06-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0015_remove_legalagency_agency_logo'),
        ('timesheet', '0007_auto_20220629_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legal_agency.businessunit'),
        ),
    ]
