# Generated by Django 3.1 on 2022-06-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_auto_20220630_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='sheet',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_set', to='timesheet.activitytype'),
        ),
    ]
