# Generated by Django 3.1 on 2022-06-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0019_remove_profile_business_unit'),
        ('timesheet', '0009_auto_20220630_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.activity'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_managment.profile'),
        ),
    ]
