# Generated by Django 3.1 on 2022-06-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_auto_20220630_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
