# Generated by Django 3.1 on 2022-07-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0011_sheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
