# Generated by Django 3.1 on 2022-07-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_activitytype_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_validated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
