# Generated by Django 3.1 on 2022-07-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_auto_20220705_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='is_deleted',
        ),
    ]
