# Generated by Django 3.1 on 2022-07-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_agency', '0017_auto_20220724_1512'),
        ('timesheet', '0015_remove_activitytype_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='business_unit',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='business_unit',
            field=models.ManyToManyField(to='legal_agency.BusinessUnit'),
        ),
    ]
