# Generated by Django 3.1 on 2021-03-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_managment', '0002_auto_20210322_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(default='Ajouter une option ici...', max_length=200),
        ),
    ]
