# Generated by Django 3.1 on 2021-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel_managment', '0003_auto_20210317_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='activity_ar',
        ),
        migrations.RemoveField(
            model_name='company',
            name='activity_fr',
        ),
        migrations.AddField(
            model_name='company',
            name='activity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
