# Generated by Django 3.1 on 2021-03-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel_managment', '0005_job_jobcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
