# Generated by Django 3.1 on 2021-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel_managment', '0006_auto_20210329_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'New'), (2, 'Valid'), (3, 'Reject')], default=1, null=True),
        ),
    ]
