# Generated by Django 3.1 on 2021-04-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel_managment', '0007_auto_20210330_1356'),
        ('candidate_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='referentiel_managment.company'),
            preserve_default=False,
        ),
    ]
