# Generated by Django 3.1 on 2021-04-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0002_auto_20210401_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='curent_devise',
            new_name='current_devise',
        ),
    ]
