# Generated by Django 3.1 on 2021-04-02 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0004_candidate_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
