# Generated by Django 3.1 on 2021-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0006_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
