# Generated by Django 3.1 on 2021-04-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel_managment', '0008_auto_20210416_1727'),
        ('candidate_managment', '0007_auto_20210405_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='referentiel_managment.company'),
        ),
    ]
