# Generated by Django 3.1 on 2021-04-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0008_auto_20210416_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
