# Generated by Django 3.1 on 2021-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0009_auto_20210417_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='disponibility',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
