# Generated by Django 3.1 on 2021-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0010_auto_20210419_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
