# Generated by Django 3.1 on 2021-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0012_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'nouveau'), (2, 'vivier')], default=1, null=True),
        ),
    ]
