# Generated by Django 3.1 on 2021-06-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0013_auto_20210531_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='disponibility',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='function',
        ),
    ]
