# Generated by Django 3.1 on 2021-06-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0014_auto_20210601_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='disponibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='function',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
