# Generated by Django 3.1 on 2021-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0015_auto_20210601_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
