# Generated by Django 3.1 on 2021-06-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0016_candidate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
