# Generated by Django 3.1 on 2022-03-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0017_candidate_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_valid',
        ),
    ]
