# Generated by Django 3.1 on 2022-03-04 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_managment', '0019_auto_20220304_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
    ]
